export const PATH_PUBLIC = {
    home: '/login',
    register: 'register',
    login: 'login',
    unauthorized: '/unauthorized',
    notFound: '/404',
  };
  
  export const PATH_DASHBOARD = {
    dashboard: '/dashboard',
    usersManagement: '/dashboard/users-management',
    updateRole: '/dashboard/update-role/:userName',
    sendMessage: '/dashboard/send-message',
    manageMessage: '/dashboard/manageMessages',
    manageUsers: '/dashboard/manageUsers',
    manageLeaves: '/dashboard/manageLeaves',
    genericManagement: '/dashboard/genericManagement',
    inbox: '/dashboard/inbox',
    allMessages: '/dashboard/all-messages',
    allUsers: '/dashboard/users',
    systemLogs: '/dashboard/system-logs',
    myLogs: '/dashboard/my-logs',
    owner: '/dashboard/owner',
    admin: '/dashboard/admin',
    manager: '/dashboard/manager',
    user: '/dashboard/user',
    userDetails: '/dashboard/username',
    updateLeaveRequest:'/dashboard/LeaveRequests',
    processLeaveRequest:'/dashboard/LeaveRequests',
    manageDepartments:'/Departments',
    updateDepartment:'/dashboard/LeaveRequests',
    updateUserDetails:'/dashboard/Update',
    projectRequest :'/dashboard/Projects',
    teamRequest : '/dashboard/Teams',
    jobTitleRequest : '/dashboard/JobTitle',
    clientRequest : '/dashboard/Clients',
    manageTimesheets : 'dashboard/Timesheet',
    manageProjects:'dashboard/Project',


    allocationByusername: '/dashboard/allocations/username',
    myAllocation: '/dashboard/my-allocations',
    allLeaveAllocations: '/dashboard/all-leaveAllocations',
    allocationByLeaveName: '/dashboard/allocation-leavename',
  };